//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDDEntity.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Alumno = new HashSet<Alumno>();
            this.Profesor = new HashSet<Profesor>();
        }
    
        public int idCurso { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaInicio { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual ICollection<Profesor> Profesor { get; set; }
    }
}
